' Kirie: xmasengine
music_kirie: DATA BYTE 15
    MUSIC G3X,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC F3,-,-,-
    MUSIC S,-,-,-
    MUSIC F3,-,-,-
    MUSIC S,-,-,-
    MUSIC G3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC D3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC G3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC F3,-,-,-
    MUSIC S,-,-,-
    MUSIC F3,-,-,-
    MUSIC S,-,-,-
    MUSIC G3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC G3,F4Z,-,-
    MUSIC S,S,-,-
    MUSIC S,S,-,-
    MUSIC S,S,-,-
    MUSIC D4,C4,-,-
    MUSIC S,S,-,-
    MUSIC S,S,-,-
    MUSIC S,S,-,-
    MUSIC C4,G4,-,-
    MUSIC S,S,-,-
    MUSIC A3,S,-,-
    MUSIC S,S,-,-
    MUSIC G3,C4,-,-
    MUSIC S,S,-,-
    MUSIC F3,S,-,-
    MUSIC S,S,-,-
    MUSIC G3,F4,-,-
    MUSIC S,S,-,-
    MUSIC S,S,-,-
    MUSIC S,S,-,-
    MUSIC S,G4,-,-
    MUSIC S,S,-,-
    MUSIC S,G4,-,-
    MUSIC S,S,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC G3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC F3,-,-,-
    MUSIC S,-,-,-
    MUSIC F3,-,-,-
    MUSIC S,-,-,-
    MUSIC G3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC D3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC G3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC F3,-,-,-
    MUSIC S,-,-,-
    MUSIC F3,-,-,-
    MUSIC S,-,-,-
    MUSIC G3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC G3,F4,-,-
    MUSIC S,S,-,-
    MUSIC S,S,-,-
    MUSIC S,S,-,-
    MUSIC D4,C4,-,-
    MUSIC S,S,-,-
    MUSIC S,S,-,-
    MUSIC S,S,-,-
    MUSIC C4,G4,-,-
    MUSIC S,S,-,-
    MUSIC A3,S,-,-
    MUSIC S,S,-,-
    MUSIC G3,C4,-,-
    MUSIC S,S,-,-
    MUSIC F3,S,-,-
    MUSIC S,S,-,-
    MUSIC G3,F4,-,-
    MUSIC S,S,-,-
    MUSIC S,S,-,-
    MUSIC S,S,-,-
    MUSIC S,G4,-,-
    MUSIC S,S,-,-
    MUSIC S,G4,-,-
    MUSIC S,S,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC G3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC G3,-,-,-
    MUSIC S,-,-,-
    MUSIC A3#,-,-,-
    MUSIC S,-,-,-
    MUSIC A4,-,-,-
    MUSIC S,-,-,-
    MUSIC A4,-,-,-
    MUSIC S,-,-,-
    MUSIC G4,-,-,-
    MUSIC S,-,-,-
    MUSIC F4,-,-,-
    MUSIC S,-,-,-
    MUSIC D4,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC -,-,-,-
    MUSIC G3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC D4,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC C4,-,-,-
    MUSIC S,-,-,-
    MUSIC A3,-,-,-
    MUSIC S,-,-,-
    MUSIC G3,-,-,-
    MUSIC S,-,-,-
    MUSIC F3,-,-,-
    MUSIC S,-,-,-
    MUSIC G3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC A3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC G3,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC S,-,-,-
    MUSIC -,-,-,-
    MUSIC REPEAT
    MUSIC STOP
